import type { AppProps } from "next/app";
import Head from "next/head";
import { QueryClient, QueryClientProvider } from "react-query";
import { GameProvider, useGameContext } from "contexts/game";

export default function App({ Component, pageProps }: AppProps) {
  const queryClient = new QueryClient();
  const { game } = useGameContext();

  return (
    <>
      <Head>
        <title>NextJS Base</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="crossOrigin"
        />
      </Head>
      <main>
        <QueryClientProvider client={queryClient}>
          <GameProvider value={game}>
            <Component {...pageProps} />
          </GameProvider>
        </QueryClientProvider>
      </main>
    </>
  );
}
